// Register

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_ERROR = "REGISTER_ERROR";


// Login


export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_ERROR = "LOGIN_ERROR";


//get pols
export const GET_POLS_SUCCESS = "GET_POLS_SUCCESS";
export const GET_POLS_ERROR = "GET_POLS_ERROR";
export const GET_POLS_REQUEST = "GET_POLS_REQUEST";


// update pol title 
export const UPDATE_POLS_TITLE_SUCCESS = "UPDATE_POLS_TITLE_SUCCESS";
export const UPDATE_POLS_TITLE_ERROR = "UPDATE_POLS_TITLE_ERROR";
export const UPDATE_POLS_TITLE_REQUEST = "UPDATE_POLS_TITLE_REQUEST";
